### ISSUE TITLE
RoomAvailabilityList has invalid JSON example

### ISSUE THREAD

**Issue by shah-smit** [MyAllocator/apidocs#1]
> {
>     "Rooms": [
>           {
>      	  "RoomId": 48,
>           "PropertyId": 1234,
>    		  "isPrivate": true,
>           "RoomName": "1-person private",
>           "RatePlanId": 0,
>           "Data": [
>             {
>               "Date": "2014-03-15",
>               "Units": 2,
>               "Price": 33,
>               "MinStay": 1,
>               "MaxStay": 7,
>               "Closed": false,
>               "ClosedForArrival": false,
>               "ClosedForDeparture": false
>             },
>             {
>               "Date": "2014-03-16",
>               "Units": 2,
>               "Price": 33,
>               "MinStay": 1,
>               "MaxStay": 7,
>               "Closed": false,
>               "ClosedForArrival": false,
>               "ClosedForDeparture": false
>             }
>           ]
>         },
>         {
>           "RoomId": 49,
>           "PropertyId": 1,
> 			 "isPrivate": false,
> 			 "PriceStrategy":
>           "RoomName": "5-person male shared",
>           "RatePlanId" : 0,
>           "Data": [
>             {
>               "Date": "2014-03-15",
>               "Units": 0,
>               "Price": 0,
>               "MinStay": 1,
>               "MaxStay": 7,
>               "Closed": false,
>               "ClosedForArrival": false,
>               "ClosedForDeparture": false
>             },
>             {
>               "Date": "2014-03-16",
>               "Units": 0,
>               "Price": 0,
>               "MinStay": 1,
>               "MaxStay": 7,
>               "Closed": false,
>               "ClosedForArrival": false,
>               "ClosedForDeparture": false
>             }
>           ]
>         }
>       }
>     }

**Comment by mopagemo** [comment]
Thanks for the bug report. I'll get the documentation updated. It might take until next week, and you probably already figured it out, but here is the correct JSON:
`{
    "Rooms": [
        {
            "Data": [
                {
                    "Closed": false,
                    "ClosedForArrival": false,
                    "ClosedForDeparture": false,
                    "Date": "2014-03-15",
                    "MaxStay": 7,
                    "MinStay": 1,
                    "Price": 33,
                    "Units": 2
                },
                {
                    "Closed": false,
                    "ClosedForArrival": false,
                    "ClosedForDeparture": false,
                    "Date": "2014-03-16",
                    "MaxStay": 7,
                    "MinStay": 1,
                    "Price": 33,
                    "Units": 2
                }
            ],
            "PropertyId": 1234,
            "RatePlanId": 0,
            "RoomId": 48,
            "RoomName": "1-person private",
            "isPrivate": true
        },
        {
            "Data": [
                {
                    "Closed": false,
                    "ClosedForArrival": false,
                    "ClosedForDeparture": false,
                    "Date": "2014-03-15",
                    "MaxStay": 7,
                    "MinStay": 1,
                    "Price": 0,
                    "Units": 0
                },
                {
                    "Closed": false,
                    "ClosedForArrival": false,
                    "ClosedForDeparture": false,
                    "Date": "2014-03-16",
                    "MaxStay": 7,
                    "MinStay": 1,
                    "Price": 0,
                    "Units": 0
                }
            ],
            "PropertyId": 1,
            "RatePlanId": 0,
            "RoomId": 49,
            "RoomName": "5-person male shared",
            "isPrivate": false
        }
    ]
}`

**Comment by shah-smit** [comment]
@mopagemo  Thanks for the immediate help. Appreciate it. :simple_smile:

I found one more invalid JSON at [ChannelList](https://myallocator.github.io/apidocs/#api-3_API_Methods-ChannelList). could you please assist me.

```
{
   "Channels" : {
      "bd" : {
         "RoomInput" : [
            {
               "length" : 256,
               "name" : "bd_type",
               "type" : "text"
            },
            {
               "length" : 256,
               "name" : "bd_type",
               "type" : "text"
            },
            {
               "name" : "bd_diff",
               "type" : "currency"
            }
         ],
         "isLive" : "true",
         "isBeta" : "true",
         "name" : "BestDay",
         "isCalendarBased" : "false",
         "signupLink" : "http://extranetbeta.bestday.com/HOME/REGISTER",
         "isLockedLogin" : "false",
         "PropertyInput" : [
            {
               "length" : 256,
               "name" : "bd_id",
               "type" : "text",
               "label" : "User ID",
               "validate" : 1
            },
            {
               "length" : 256,
               "name" : "bd_password",
               "type" : "text",
               "label" : "Password"
            },
            {
               "length" : 256,
               "name" : "bd_propid",
               "type" : "text",
               "label" : "Property ID"
            }
         ]
      },
      "rec" : {
         "RoomInput" : [
            {
               "length" : 50,
               "name" : "rec_type",
               "type" : "text"
            },
            {
               "name" : "rec_rate",
               "type" : "integer"
            },
            {
               "name" : "rec_diff",
               "type" : "currency"
            }
         ],
         "isLive" : "true",
         "isBeta" : "false",
         "name" : "Reconline",
         "isCalendarBased" : "false",
         "signupLink" : "http://www.reconline.com/e/hotels.html",
         "isLockedLogin" : "true",
         "PropertyInput" : [
            {
               "activation" : 1,
               "name" : "rec_id",
               "label" : "Hotel ID",
               "validate" : 1
            },
            {
               "activation" : 1,
               "stored" : 0,
               "name" : "rec_city",
               "label" : "City"
            }
         ]
      }
	}
```

**Comment by mopagemo** [comment]
Just add a closing curly bracket to the end. I'll make sure to get this fixed too. Thanks again for pointing it out.

**Comment by mopagemo** [comment]
Spec fixed.
